artifact_location: file:///home/iman/Eksperimen_SML_ImanRohiman/Membangun_model/mlruns/685649157302216494
creation_time: 1782125178956
experiment_id: '685649157302216494'
last_update_time: 1782125178956
lifecycle_stage: active
name: eksperimen_model
